// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEg9LEM-bbSMlMGJuS391KjcSWdxxdAc',
    appId: '1:709161327858:web:8baf366059a6324dd5446b',
    messagingSenderId: '709161327858',
    projectId: 'auth-firebase-lesson-53bd0',
    authDomain: 'auth-firebase-lesson-53bd0.firebaseapp.com',
    storageBucket: 'auth-firebase-lesson-53bd0.appspot.com',
    measurementId: 'G-MWGECEWMQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDawDHbm5jnpmTx3KETro_D-JhbWzwi2D0',
    appId: '1:709161327858:android:95c9b0cef3fe4f9ed5446b',
    messagingSenderId: '709161327858',
    projectId: 'auth-firebase-lesson-53bd0',
    storageBucket: 'auth-firebase-lesson-53bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAap9A8CEqEd8rMqITWw6mmIdwN1pBQWHI',
    appId: '1:709161327858:ios:005d116f6f1c9df5d5446b',
    messagingSenderId: '709161327858',
    projectId: 'auth-firebase-lesson-53bd0',
    storageBucket: 'auth-firebase-lesson-53bd0.appspot.com',
    iosBundleId: 'com.example.lesson36FirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAap9A8CEqEd8rMqITWw6mmIdwN1pBQWHI',
    appId: '1:709161327858:ios:e35c6fb2d9d115d7d5446b',
    messagingSenderId: '709161327858',
    projectId: 'auth-firebase-lesson-53bd0',
    storageBucket: 'auth-firebase-lesson-53bd0.appspot.com',
    iosBundleId: 'com.example.lesson36FirebaseAuth.RunnerTests',
  );
}
